# Generated by Django 6.0.4 on 2026-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("home_about", "Главная: О ресторане"),
                            ("home_services", "Главная: Услуги"),
                            ("home_contact", "Главная: Контакты"),
                            ("about_history", "О ресторане: История"),
                            ("about_mission", "О ресторане: Миссия и ценности"),
                            ("about_team", "О ресторане: Команда"),
                            ("footer", "Подвал сайта"),
                        ],
                        help_text="Выберите раздел сайта для редактирования",
                        max_length=50,
                        unique=True,
                        verbose_name="Раздел",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, verbose_name="Содержание")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Контент сайта",
                "verbose_name_plural": "Контент сайта",
            },
        ),
    ]
